_target_: src.tasks.cls.KONKURS

name: bankruptcy
max_length: 2560
no_sep: False

pooled: False
num_pooled_sep: 0

# Augmentation
p_sequence_timecut: 0.0
p_sequence_resample: 0.4
p_sequence_abspos_noise: 0.1
p_sequence_hide_background: 0.01
p_sentence_drop_tokens: 0.01

shuffle_within_sentences: true