defaults:
  - _self_
  - /experiment: "???"

# Values for the different experiments
seed: 2024
version: "0.0"
implementation: "placeholder"
name: "placeholder"

local_path: "master_thesis" #"Library/CloudStorage/OneDrive-DanmarksTekniskeUniversitet/Virk2Vec"
user_path: "/zhome/d5/c/146512/" #"/Users/nikolaibeckjensen/"

# checkpoint
ckpt_path: /zhome/d5/c/146512/master_thesis/checkpoints