defaults:
  - /data_new/corpus@corpus: bankruptcy_set
  - /data_new/vocabulary@vocabulary: global_set
  - /task@task: cls_tab

_target_: src.data_new.datamodule.CLSDataModule

batch_size: 8
num_workers: 2