defaults:
  - /data/corpus@corpus: employee_set
  - /data/vocabulary@vocabulary: global_set_no_shortterm
  - /task@task: cls

_target_: src.data.datamodule.MultiCLSDataModule

batch_size: 8
num_workers: 2