defaults:
  - /data/corpus@corpus: employee_set_6mon
  - /data/vocabulary@vocabulary: global_set
  - /task@task: cls

_target_: src.data.datamodule.CLSDataModuleNoUpsampling

batch_size: 8
num_workers: 2