defaults:
  - /data/corpus@corpus: global_set
  - /data/vocabulary@vocabulary: global_set
  - /task@task: mlm

_target_: src.data.datamodule.C2VDataModule

batch_size: 8
num_workers: 0

### If you want to train the model on subsets of data
subset: True
subset_id: 0 #max 1